[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "warnings"
version = "1.0.0"
description = "Manage warnings in YTArchive database"
readme = ""
requires-python = ">=3.7"
dependencies = []

[project.scripts]
warnings = "main:main"
